id: I2DFCCE0C
default_language: bo
source: ''
initial_creation_type: tmx
imported: 2022-12-15 07:24:04.885758+00:00
last_modified: 2022-12-15 07:24:04.885768+00:00
source_metadata:
  creationtool: InterText
  creationtoolversion: '1.0'
  datatype: PlainText
  segtype: block
  adminlang: en-us
  srclang: bo
  o-tmf: XML aligned text
  eft-text-id: UT22084-048-001
  eft-text-version: 1.2.3 2020
  title: Toh_101-Upholding_the_Roots_of_Virtue-v2
bases:
  8FF8:
    source_metadata: null
    order: 1
    base_file: 8FF8.txt
    statistics: null
copyright:
  status: Unknown
  notice: ''
